// Generated by CoffeeScript 1.11.1
(function() {
  var base,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  (base = Gruff.Views).Debates || (base.Debates = {});

  Gruff.Views.Debates.EditTitleView = (function(superClass) {
    extend(EditTitleView, superClass);

    function EditTitleView() {
      this.handleKeys = bind(this.handleKeys, this);
      this.close = bind(this.close, this);
      return EditTitleView.__super__.constructor.apply(this, arguments);
    }

    EditTitleView.prototype.initialize = function(options) {
      this.template = _.template($('#debate-edit-title-template').text());
      this.titleEl = options.titleEl;
      this.zoomEl = options.zoomEl;
      return this.model.bind("change:errors", (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
    };

    EditTitleView.prototype.save = function() {
      var newTitle;
      this.model.unset("errors");
      newTitle = this.editTitleField.val();
      this.model.setTitle(newTitle);
      return $.ajax({
        type: "POST",
        url: "/debates/titles/new",
        data: {
          _id: this.model.linkableId(),
          title: newTitle
        },
        success: (function(_this) {
          return function(data) {
            $(_this.titleEl).html(newTitle);
            return _this.close();
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, type) {
            return _this.handleRemoteError(jqXHR);
          };
        })(this)
      });
    };

    EditTitleView.prototype.render = function() {
      var json;
      json = this.model.fullJSON();
      if (!$(this.el).hasClass('.title')) {
        this.el = $(this.el).parents('.title')[0];
      }
      $(this.el).append(this.template(json));
      if (this.titleEl == null) {
        this.titleEl = $(this.el).find('a.title-link');
      }
      $(this.titleEl).hide();
      if (this.zoomEl == null) {
        this.zoomEl = $(this.el).find('a.zoom-link');
      }
      $(this.zoomEl).hide();
      this.editTitleField = $(this.el).find('#' + this.model.linkableId() + "-title-field");
      this.editTitleField.bind("keydown", this.handleKeys);
      this.editTitleField.bind("blur", this.close);
      this.editTitleField.show();
      this.editTitleField.focus();
      return this;
    };

    EditTitleView.prototype.close = function() {
      $(this.titleEl).show();
      $(this.zoomEl).show();
      this.editTitleField.remove();
      return this.unbind();
    };

    EditTitleView.prototype.handleKeys = function(e) {
      if (e.keyCode === 13) {
        this.save();
        return false;
      } else if (e.keyCode === 27) {
        this.close();
        return false;
      } else {
        return true;
      }
    };

    return EditTitleView;

  })(Backbone.View);

}).call(this);
