/* 
 * Provides functions for any domain model that can have an id
 * (as generated by MongoDB)
 */

Identifiable = function() {
};

Identifiable.prototype.linkableId = function() {
    return this._id.toHexString();
};


exports.Identifiable = Identifiable;
